"""Four-bar geometry used by the planar 3R workspace reduction."""

from __future__ import annotations

from dataclasses import dataclass
from math import isclose


@dataclass(frozen=True, slots=True)
class FourBar:
    """Ordered four-bar lengths.

    The loop order is:

        ground -> input -> coupler -> output -> ground

    For the planar 3R workspace reduction:

        ground = distance from robot base to fixed end-effector position
        input = terminal link l3
        coupler = middle link l2
        output = proximal link l1
    """

    ground: float
    input: float
    coupler: float
    output: float

    def __post_init__(self) -> None:
        for name, value in (
            ("ground", self.ground),
            ("input", self.input),
            ("coupler", self.coupler),
            ("output", self.output),
        ):
            if value < 0.0:
                raise ValueError(f"{name} must be nonnegative")
        if self.input == 0.0 or self.coupler == 0.0 or self.output == 0.0:
            raise ValueError("moving links must have positive length")

    @property
    def lengths(self) -> tuple[float, float, float, float]:
        return (self.ground, self.input, self.coupler, self.output)

    @property
    def grashof_margin(self) -> float:
        """Return P + Q - S - L.

        Positive: Grashof
        Zero: change-point
        Negative: non-Grashof
        """
        ordered = sorted(self.lengths)
        shortest, p, q, longest = ordered
        return p + q - shortest - longest

    def is_grashof(self, *, tol: float = 1e-12) -> bool:
        return self.grashof_margin >= -tol

    def inversion_type(self, *, tol: float = 1e-12) -> str:
        """Return a conservative conventional linkage classification.

        Exact input rotatability should be determined with
        ``input_can_fully_rotate``. Tied shortest links are intentionally
        reported as special cases rather than forced into a generic label.
        """
        margin = self.grashof_margin
        if margin < -tol:
            return "non-grashof double-rocker"
        if abs(margin) <= tol:
            return "change-point"

        minimum = min(self.lengths)
        shortest_indices = [
            index
            for index, value in enumerate(self.lengths)
            if isclose(value, minimum, abs_tol=tol, rel_tol=0.0)
        ]
        if len(shortest_indices) != 1:
            return "special grashof (tied shortest links)"

        shortest = shortest_indices[0]
        if shortest == 0:
            return "double-crank"
        if shortest == 2:
            return "grashof double-rocker"
        return "crank-rocker"

    def input_distance_bounds(self) -> tuple[float, float]:
        """Distance from the far ground pivot to the input-link tip."""
        return (abs(self.ground - self.input), self.ground + self.input)

    def connector_distance_bounds(self) -> tuple[float, float]:
        """Distances the coupler-output two-link chain can span."""
        return (abs(self.output - self.coupler), self.output + self.coupler)

    def input_can_fully_rotate(self, *, tol: float = 1e-12) -> bool:
        """Test exact full input rotation from loop-closure geometry.

        Full rotation is possible iff every distance generated by the input
        crank can be closed by the coupler-output two-link chain.
        """
        input_min, input_max = self.input_distance_bounds()
        connector_min, connector_max = self.connector_distance_bounds()
        return (
            input_min >= connector_min - tol
            and input_max <= connector_max + tol
        )
